--============ TYPES ========================
--CREATE TYPE shiftStatus AS ENUM ('cancelled', 'coming', 'completed');
--CREATE TYPE organizationType AS ENUM ('company', 'event');
--CREATE TYPE applicationStatus AS ENUM ('confirmed', 'accepted', 'refused', 'pending', 'employee_canceled', 'boss_canceled');
--CREATE TYPE salaryType AS ENUM ('hourly', 'fix');
--CREATE TYPE gender AS ENUM ('male', 'female', 'else');
-- Je comprends pas Npgsql pour C# alors je transforme les Types en Domaines, c'est la vie...
-- CREATE TYPE userRole AS ENUM ('employer', 'employee', 'admin');